users=[{"id":1,"name":"Rahul","gender":"Male","loc":"New Delhi"},
{"id":2,"name":"Sonia","gender":"Female","loc":"New Delhi"},
{"id":3,"name":"Priyanka","gender":"Female","loc":"New Delhi"},
{"id":4,"name":"Modi","gender":"Male","loc":"New Delhi"},
{"id":5,"name":"Rajni","gender":"Male","loc":"New Delhi"},
{"id":6,"name":"Vijay","gender":"Male","loc":"Chennai"},
{"id":7,"name":"VS","gender":"Male","loc":"Chennai"},
{"id":8,"name":"Nicolai","gender":"Male","loc":"Itatskiy"},
{"id":9,"name":"Blondie","gender":"Female","loc":"Rerawere"},
{"id":10,"name":"Clotilda","gender":"Female","loc":"Jämsänkoski"},
{"id":11,"name":"King","gender":"Male","loc":"Montpellier"},
{"id":12,"name":"Chrotoem","gender":"Male","loc":"Norrköping"},
{"id":13,"name":"Elisabet","gender":"Female","loc":"Surup"},
{"id":14,"name":"Afton","gender":"Female","loc":"Benisheikh"},
{"id":15,"name":"Marleah","gender":"Female","loc":"Limoeiro de Anadia"},
{"id":16,"name":"Ewell","gender":"Male","loc":"Tam Bình"},
{"id":17,"name":"Johann","gender":"Male","loc":"Dayr as Sūdān"},
{"id":18,"name":"Gun","gender":"Male","loc":"Eloy Alfaro"},
{"id":19,"name":"Britta","gender":"Female","loc":"Kirs"},
{"id":20,"name":"Merv","gender":"Male","loc":"Liwonde"},
{"id":21,"name":"Rene","gender":"Male","loc":"Samacá"},
{"id":22,"name":"Avis","gender":"Female","loc":"København"},
{"id":23,"name":"Kingston","gender":"Male","loc":"Wołomin"},
{"id":24,"name":"Bertrand","gender":"Male","loc":"Penamacor"},
{"id":25,"name":"Irv","gender":"Male","loc":"Ho"},
{"id":26,"name":"Andras","gender":"Male","loc":"Bergvliet"},
{"id":27,"name":"Alfie","gender":"Male","loc":"Kongtian"},
{"id":28,"name":"Carmelle","gender":"Female","loc":"Adela"},
{"id":29,"name":"Clyve","gender":"Male","loc":"Barrancas"},
{"id":30,"name":"Baron","gender":"Male","loc":"Velykyy Burluk"},
{"id":31,"name":"Adelle","gender":"Female","loc":"Dmanisi"},
{"id":32,"name":"Alida","gender":"Female","loc":"Crépy-en-Valois"},
{"id":33,"name":"Manny","gender":"Male","loc":"Mujães"},
{"id":34,"name":"Eugine","gender":"Female","loc":"Canedo"},
{"id":35,"name":"Raimondo","gender":"Male","loc":"Ōzu"},
{"id":36,"name":"Waylan","gender":"Male","loc":"Oakland"},
{"id":37,"name":"Alene","gender":"Female","loc":"Serowe"},
{"id":38,"name":"Casi","gender":"Female","loc":"Magang"},
{"id":39,"name":"Ole","gender":"Bigender","loc":"Sîr ed Danniyé"},
{"id":40,"name":"Stacia","gender":"Genderfluid","loc":"Ringim"},
{"id":41,"name":"Jammal","gender":"Agender","loc":"Yamaga"},
{"id":42,"name":"Helyn","gender":"Female","loc":"Panjāb"},
{"id":43,"name":"Dexter","gender":"Male","loc":"As Suqaylibīyah"},
{"id":44,"name":"Goober","gender":"Male","loc":"Kawaliwu"},
{"id":45,"name":"Arin","gender":"Male","loc":"Xiachu"},
{"id":46,"name":"Linoel","gender":"Male","loc":"Bronx"},
{"id":47,"name":"Ange","gender":"Male","loc":"Hashtpar"},
{"id":48,"name":"Pauletta","gender":"Female","loc":"Nizhniy Tagil"},
{"id":49,"name":"Alaric","gender":"Male","loc":"Seixo da Beira"},
{"id":50,"name":"Ailyn","gender":"Female","loc":"Tuchola"},
{"id":51,"name":"Elke","gender":"Non-binary","loc":"Az̧ Z̧alī‘ah"},
{"id":52,"name":"Adriana","gender":"Female","loc":"Negotino"},
{"id":53,"name":"Aylmar","gender":"Male","loc":"Mislak"},
{"id":54,"name":"Edmund","gender":"Male","loc":"Anulid"},
{"id":55,"name":"Kirstin","gender":"Female","loc":"Três Rios"},
{"id":56,"name":"Sheilakathryn","gender":"Female","loc":"Longos"},
{"id":57,"name":"Briant","gender":"Male","loc":"Saguenay"},
{"id":58,"name":"Porter","gender":"Male","loc":"Le Bourget-du-Lac"},
{"id":59,"name":"Leroy","gender":"Male","loc":"Achoma"},
{"id":60,"name":"Brittan","gender":"Female","loc":"Danxi"},
{"id":61,"name":"Demetra","gender":"Female","loc":"Libu"},
{"id":62,"name":"Merlina","gender":"Female","loc":"El Bálsamo"},
{"id":63,"name":"Marris","gender":"Female","loc":"Rio"},
{"id":64,"name":"Gwyneth","gender":"Female","loc":"Cazin"},
{"id":65,"name":"Ina","gender":"Female","loc":"Ozëry"},
{"id":66,"name":"Kendell","gender":"Male","loc":"Bābolsar"},
{"id":67,"name":"Emanuele","gender":"Male","loc":"Kwaluseni"},
{"id":68,"name":"Wendie","gender":"Agender","loc":"Itu"},
{"id":69,"name":"Hasheem","gender":"Male","loc":"Karangbayat"},
{"id":70,"name":"Zahara","gender":"Female","loc":"Tuamese"},
{"id":71,"name":"Liam","gender":"Male","loc":"Velyka Pysarivka"},
{"id":72,"name":"Quint","gender":"Male","loc":"Notre-Dame-des-Prairies"},
{"id":73,"name":"Lincoln","gender":"Agender","loc":"Serra"},
{"id":74,"name":"Carin","gender":"Female","loc":"Federal"},
{"id":75,"name":"Nancy","gender":"Female","loc":"Tsiatsan"},
{"id":76,"name":"Noemi","gender":"Female","loc":"Santana"},
{"id":77,"name":"Shay","gender":"Male","loc":"Rancho Viejo"},
{"id":78,"name":"Parsifal","gender":"Male","loc":"Ciudad Bolivia"},
{"id":79,"name":"Aimil","gender":"Non-binary","loc":"Majia"},
{"id":80,"name":"Hortensia","gender":"Non-binary","loc":"Qiaotou"},
{"id":81,"name":"Felix","gender":"Male","loc":"Bratislava"},
{"id":82,"name":"Rees","gender":"Male","loc":"Ribeira Quente"},
{"id":83,"name":"Carmencita","gender":"Female","loc":"Melfi"},
{"id":84,"name":"Hasheem","gender":"Male","loc":"Otavi"},
{"id":85,"name":"Uriah","gender":"Male","loc":"Stari Banovci"},
{"id":86,"name":"Iorgos","gender":"Male","loc":"Cergy-Pontoise"},
{"id":87,"name":"Angeline","gender":"Female","loc":"Río Grande"},
{"id":88,"name":"Rees","gender":"Polygender","loc":"Jiuting"},
{"id":89,"name":"Thatch","gender":"Male","loc":"Vysočany"},
{"id":90,"name":"Lonnie","gender":"Male","loc":"Junyang"},
{"id":91,"name":"Albert","gender":"Male","loc":"Dologon"},
{"id":92,"name":"Cameron","gender":"Male","loc":"Yutan"},
{"id":93,"name":"Urbanus","gender":"Male","loc":"Sankwia"},
{"id":94,"name":"Elfie","gender":"Female","loc":"Mocun"},
{"id":95,"name":"Mona","gender":"Polygender","loc":"Owo"},
{"id":96,"name":"Elladine","gender":"Female","loc":"Małkinia Górna"},
{"id":97,"name":"Wilfrid","gender":"Male","loc":"Honghualiangzi"},
{"id":98,"name":"Junie","gender":"Female","loc":"Hengfeng"},
{"id":99,"name":"Maryanna","gender":"Polygender","loc":"Pytalovo"},
{"id":100,"name":"Tally","gender":"Female","loc":"Tilburg"}]



for user in users:
    if user['gender'] == "Male":
        print(user.get('name'))